version: '3.7'

services:
  db:
    container_name: celcatweb_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-password
      MYSQL_DATABASE: celcatweb
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    environment:
      DATABASE_URL: "mysql://root:my-password@db:3306/celcatweb"
    ports:
      - "3300:3000"
    depends_on:
      - db
