import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body className={inter.className}>
      <Navbar>
          <li><Link href="/teachers">Professeurs</Link></li>
          <li>
              <Link href="/groups">Groupes</Link>
          </li>
          <li><Link href="/modules">Module</Link></li>
      </Navbar>
      {children}
      </body>
    </html>
  );
}
